p4/flask_app/movies/routes.py
import os, requests
from requests import get
import base64,io
from io import BytesIO
from flask import Flask, Blueprint, json, render_template, url_for, redirect, request, flash, session
from flask_login import current_user

from .. import movie_client
from ..forms import MovieReviewForm, SearchForm, MovieRatingForm
from ..models import User, Review, Rating
from ..utils import current_time

from spotipy import Spotify
from spotipy import SpotifyOAuth
from spotipy.cache_handler import FlaskSessionCacheHandler

from ..client import SpotifyClient

app = Flask(__name__)
app.config['SECRET_KEY'] = os.urandom(64)

client_id = '5817050472aa40e488cfe5e5d80dd6be'
client_secret = 'a6327884a1fd428683b2e5ec2ebfa3d8'
redirect_uri = 'http://localhost:5000/callback'
scope = ['user-top-read']

cache_handler = FlaskSessionCacheHandler(session)
sp_oauth = SpotifyOAuth(
    client_id=client_id,
    client_secret=client_secret,
    redirect_uri=redirect_uri,
    scope=scope,
    cache_handler=cache_handler,
    show_dialog=True,
)
sp = Spotify(auth_manager=sp_oauth)
spotify_client = None

albums = Blueprint("albums", __name__)
""" ************ Helper for pictures uses username to get their profile picture************ """

def get_b64_img(username):
    user = User.objects(username=username).first()
    
    sp_user_data = sp.me()
    spotify_profile_pic_url = sp_user_data.get("images", [{}])[0].get("url")
    
    if spotify_profile_pic_url:
        image_data = requests.get(spotify_profile_pic_url).content
        return base64.b64encode(image_data).decode()
    
    if user.profile_pic:
        bytes_im = io.BytesIO(user.profile_pic.read())
        image = base64.b64encode(bytes_im.getvalue()).decode()
        return image
    
    print("none")
    return None  


""" ************ View functions ************ """

@albums.route('/callback')
def callback():
    if request.args.get('error') == 'access_denied':
        auth_url = sp_oauth.get_authorize_url()
        return render_template('403.html', auth_url=auth_url)
    
    global spotify_client
    sp_oauth.get_access_token(request.args['code'])
    spotify_client = SpotifyClient(sp_oauth.get_access_token()['access_token'])
    return redirect(url_for('albums.index'))


@albums.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if not sp_oauth.validate_token(cache_handler.get_cached_token()):
        auth_url = sp_oauth.get_authorize_url()
        return redirect(auth_url)

    if form.validate_on_submit():
        return redirect(url_for("albums.query_results", query=form.search_query.data))
    
    return render_template("index.html", form=form, name=sp.me()["display_name"], auth_url=sp_oauth.get_authorize_url())

@albums.route("/top-songs", methods=["GET"])
def top_songs():
    top_songs = sp.current_user_top_tracks(5)
    top_songs = list(map(lambda x: {
        "name": x["name"],
        "artist": x["artists"][0]["name"],
        "image": x["album"]["images"][0]["url"]

    }, top_songs["items"]))

    return render_template("top_songs.html", top_songs=top_songs, name=sp.me()["display_name"], auth_url=sp_oauth.get_authorize_url())

@albums.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = spotify_client.search(query)
    except ValueError as e:
        return render_template("query.html", error_msg=str(e), name=sp.me()["display_name"], auth_url=sp_oauth.get_authorize_url())

    return render_template("query.html", results=results, name=sp.me()["display_name"], auth_url=sp_oauth.get_authorize_url())


@albums.route("/albums/<album_id>", methods=["GET", "POST"])
def album_detail(album_id):
    try:
        result = spotify_client.get_album_details(album_id)
    except ValueError as e:
        return render_template("album_detail.html", error_msg=str(e), name=sp.me()["display_name"], auth_url=sp_oauth.get_authorize_url())
    
    username = sp.me()["display_name"]
    form_review = MovieReviewForm()
    form_rating = MovieRatingForm()
    if form_rating.validate_on_submit():
        print("HERE")
        rating = Rating(
            rating=form_rating.movieRating.data,
            imdb_id=album_id,
            commenter=current_user._get_current_object(),
            date=current_time(),
        )

        rating.save()

        return redirect(request.path)
    
    if form_review.validate_on_submit():
        review = Review(
            commenter=current_user._get_current_object(),
            content=form_review.text.data,
            date=current_time(),
            imdb_id=album_id,
            movie_title=result['name'],
            image=get_b64_img(username)
        )

        review.save()

        return redirect(request.path)

    reviews = Review.objects(imdb_id=album_id)
    ratings = Rating.objects(imdb_id=album_id)
    avg = 0
    for rating in ratings:
        avg += rating.rating
    if len(ratings) > 0:
        avg = avg/(len(ratings))
    print(avg)
    return render_template(
        "album_detail.html", form_review=form_review, album=result, reviews=reviews, rating=avg, form_rating=form_rating, ratings = ratings, 
        name=username, auth_url=sp_oauth.get_authorize_url()
    )

@albums.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    print("user", user)
    if not user:
        error_message = f"User '{username}' not found!"
        return render_template("user_detail.html", error=error_message, user=username)
    
    print(username)
    img = get_b64_img(username)
    
    reviews = Review.objects(commenter=user)
    
    return render_template("user_detail.html", username= username, user=user, reviews=reviews, image=img, error=None)

p4/flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User

users = Blueprint("users", __name__)

""" ************ User Management views ************ """


# TODO: implement
@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('movies.index'))
    
    form = RegistrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password=hashed_password)
            user.save()
            return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("movies.index"))

    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.objects(username=form.username.data).first()

            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('users.account'))
            else:
                flash("Failed to log in!")
    return render_template("login.html", form=form)


# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('movies.index'))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            user = User.objects(username=current_user.username).first()
            user.modify(username=update_username_form.username.data)
            user.save()
            return redirect(url_for('users.account'))

        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            user = User.objects(username=current_user.username).first()
            image = update_profile_pic_form.picture.data
            filename = secure_filename(image.filename)
            content_type = f'images/{filename[-3:]}'
            if user.profile_pic.get() is None:
                user.profile_pic.put(image.stream, content_type=content_type)
            else:
                user.profile_pic.replace(image.stream, content_type=content_type)
            user.save()
            return redirect(url_for('users.account'))

    # TODO: handle get requests
    user = User.objects(username=current_user.username).first()
    bytes_im = BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return render_template("account.html", update_username_form=update_username_form, update_profile_pic_form=update_profile_pic_form, image=image, username=current_user.username)

p4/flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if image %}
        {# Profile picture #}
        <img class="rounded-2xl h-24 w-24" src="data:image/png;base64,{{image}}" alt="image">
    {% endif %}

    <h2> Welcome, {{ username }}!</h2>

</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Username
    </h3>
    <form class="review-form" method="POST" action="">
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username.label }}
            {{ update_username_form.username(class="form-content") }}
            {% if update_username_form.username.errors %}
            <div class="error" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Profile Picture
    </h3>
    <form class="review-form" method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label }}
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="error" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<div class="flex justify-center">
    <a href="{{ url_for('albums.user_detail', username=username) }}">User Reviews</a>
</div>
{% endblock %}

p4/flask_app/templates/album_detail.html
{% extends "header.html" %} 
{% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

{% if album %}

{# Display card for the album details #}
<div class="movie-container">
  <ul class="movie-info">
    <div class="movie-title"> {{ album.name }}
    </div>
    <img class="movie-img" alt="alt text" src="{{ album.image.url }}" />
    <li class="opacity-100 md:px-4"><b>Released: </b> {{ album.release_date }} </li>
    <li class="opacity-40 md:px-4"><b>Artist:</b> {{ album.artist_name }}</li>
    <li class="opacity-40 md:px-4"><b>Total Tracks:</b> {{ album.total_tracks }}</li>
    <li class="opacity-40 md:px-4"><b>Popularity:</b> {{ album.popularity }}</li>
    <li class="md:px-4"><a href="{{album.url}}">Link to Album</a></li>
  </ul>

  {# Reviews #}
  <div class="reviews">
    <form method="POST" action="" class="review-form">
      {{ form_rating.csrf_token }}
      <div class="form-group review-input">
        {{ form_rating.movieRating.label }} {{ form_rating.movieRating() }}
      </div>
      {{ form_rating.submit(class="review-button") }}
    </form>
    
    {# Ratings display #}
    {% if ratings %}
      <h2 class="ratings-title">Individual Ratings</h2>
      <ul class="ratings-container">
        {% for r in ratings %}
          <li class="rating-item">
            <div class="rating-date">{{ r.date }}</div>
            {% if r.commenter %}
              <a class="rating-user" href="{{ url_for('albums.user_detail', username=r.commenter.username) }}">
                @{{ r.commenter.username }}
              </a>
            {% endif %}
            <div class="rating-value">Rating: {{ r.rating }} Stars</div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No ratings yet.</p>
    {% endif %}
  
    <h1 class="reviews-title"> Reviews
      <small class="reviews-count"> {{ reviews | length }} reviews </small>
    </h1>
    <ul class="review-container">
      {% for review in reviews %}
        <li class="review flex gap-2">
          <img class="h-20 w-20 rounded-lg" src="data:image/png;base64,{{review.image}}" alt="" />
          <div class="w-full">
            <span class="review-date">{{ review.date }}</span>
            <a class="review-commenter" href="{{ url_for('albums.user_detail', username=review.commenter.username) }}">
              @{{ review.commenter.username }}
            </a>
            <p class="review-content">{{ review.content }}</p>
          </div>
        </li>
      {% endfor %}
    </ul>

    {# Movie review submission form always visible #}
    <div class="container mx-auto">
      <form method="POST" action="" class="review-form">
        {{ form_review.csrf_token }}
        <div class="form-group review-input">
          {{ form_review.text.label }} {{ form_review.text(class="form-content") }}
          {% if form_review.text.errors %}
            <div class="error" role="alert">
              {% for error in form_review.text.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        {{ form_review.submit(class="review-button") }}
      </form>
    </div>
    
  </div>
  <div class="w-0 lg:w-96"></div>
</div>
{% endif %} 
{% endblock content %}

p4/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='compiled.css')}}"
    />
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Spotify Song Database</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

p4/flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('albums.index') }}">
        <span class="hidden sm:block">Spotify Songs</span>
        <span class="block sm:hidden">Home</span>
    </a>
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('albums.top_songs') }}">Account: {{name}}</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-red-400/20 hover:!bg-red-500/50 !text-red-400 hover:!text-red-300" href="{{ auth_url }}">Logout</a>
    </div>
</nav>
{% block content %}{% endblock %}{% endblock %}

p4/flask_app/templates/index.html
{% extends "header.html" %} {% block content %}
<div class="main-container">
  <div class="decoration-main-container"><div class="decoration-main"></div></div>
  <h2 class="main-title"> Search an album/artist </h2>
  <form class="searchbar" action="/" method="POST">
    {{ form.csrf_token }}
    {{ form.search_query(class="form-control", placeholder="album/artist name") }}

    {% if form.search_query.errors %}
      <div class="error" role="alert">
        {% for error in form.search_query.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% endif %}
    
    {{ form.submit(class="form-button") }}
  </form>
</div>
{% endblock %}

p4/flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

p4/flask_app/templates/movie_detail.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

{% if movie %}

{# Display card for the movie details #}
<div class="movie-container">
  <ul class="movie-info">
    <div class="movie-title"> {{ movie.name }}
    </div>
    <img class="movie-img" alt="alt text" src="{{ movie.image.url }}" />
    <li class="opacity-100 md:px-4"><b>Released: </b> {{ movie.release_date }} </li>
    <li class="opacity-40 md:px-4"><b>Artist:</b> {{ movie.artist_name }}</li>
    <li class="opacity-40 md:px-4"><b>Total Tracks:</b> {{ movie.total_tracks }}</li>
    <li class="opacity-40 md:px-4"><b>Popularity:</b> {{ movie.popularity }}</li>
    <li class="md:px-4"><a href="{{movie.url}}">Link to Album</a></li>
  </ul>

  {# Reviews #}
  <div class="reviews">
    <form method="POST" action="" class="review-form">
      {{ form_rating.csrf_token }}
      <div class="form-group review-input">
        {{ form_rating.movieRating.label }} {{ form_rating.movieRating() }}
      </div>
      {{ form_rating.submit(class="review-button") }}
    </form>
    
    {# Ratings display #}
      {% if ratings %}
      <h2 class="ratings-title">Individual Ratings</h2>
      <ul class="ratings-container">
        {% for r in ratings %}
          <li class="rating-item">
            <div class="rating-date">{{ r.date }}</div>
            {% if r.commenter %}
              <a class="rating-user" href="{{ url_for('movies.user_detail', username=r.commenter.username) }}">
                @{{ r.commenter.username }}
              </a>
            {% endif %}
            <div class="rating-value">Rating: {{ r.rating }} Stars</div>
            {# <div class="rating-user">By: @{{ r.commenter.username }}</div> #}
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No ratings yet.</p>
      {% endif %}
  
    <h1 class="reviews-title"> Reviews
      <small class="reviews-count"> {{ reviews | length }} reviews </small>
    </h1>
    <ul class="review-container">
      {% for review in reviews %}
        <li class="review flex gap-2">
          <img class="h-20 w-20 rounded-lg" src="data:image/png;base64,{{review.image}}" alt="" />
          <div class="w-full">
            <span class="review-date">{{ review.date }}</span>
            <a class="review-commenter" href="{{ url_for('movies.user_detail', username=review.commenter.username) }}">
              @{{ review.commenter.username }}
            </a>
            <p class="review-content">{{ review.content }}</p>
          </div>
        </li>
      {% endfor %}
    </ul>
{# #}
    {% if current_user.is_authenticated %}
      {# Movie review submission form #}
      <div class="container mx-auto">
        <form method="POST" action="" class="review-form">
          {{ form_review.csrf_token }}
          <div class="form-group review-input">
            {{ form_review.text.label }} {{ form_review.text(class="form-content") }}
            {% if form_review.text.errors %}
              <div class="error" role="alert">
                {% for error in form_review.text.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          {{ form_review.submit(class="review-button") }}
        </form>
      </div>
    {% endif %}
  </div>
  <div class="w-0 lg:w-96"></div>
</div>
{% endif %} {% endblock content %}

p4/flask_app/templates/query.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

<div class="results-container">
  <div class="decoration-container"><div class="decoration"></div></div>
  {% for result in results %}
  <a 
    href="{{ url_for('albums.album_detail', album_id=result.id) }}"
    class="group movie-card"
  >
    <img src="{{ result.image.url }}" class="movie-card-img" alt="missing" />
    <h4 class="movie-card-content"> {{ result.name }}</h4>
    <h5 class="movie-card-content"> Released: {{ result.release_date }} </h5>
  </a>
  {% endfor %}
</div>

{% endblock %}

p4/flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Registration</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>
<!-- Registration Form: -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="error" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="error" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>

{% endblock %}

p4/flask_app/templates/top_songs.html
{% extends "header.html" %} {% block content %}
<div class="main-container">
  <div class="decoration-main-container"><div class="decoration-main"></div></div>

  <div class="flex justify-center">

    {# Link to see all of the current user's reviews #}

    <a href="{{ url_for('albums.user_detail', username=current_user.username) }}" class="review-button">

        All Reviews

    </a>

</div>
  <h2 class="main-title"> Top 5 Songs </h2>
  <hr>
  {% for song in top_songs %}
    <div class="songs-container">
        <div class="text">
            <div style="font-weight: 700;">{{loop.index}}. {{song.name}}</div>
            <div>Artist: {{song.artist}}</div>
        </div>
        <img src="{{song.image}}" width="400">
    </div>
    <hr>
  {% endfor %}
</div>
{% endblock %}

p4/flask_app/templates/user_detail.html
{% extends "header.html" %} {% block content %}

{% if error %}

    <b class="text-red-400" role="alert">

        {{ error }}

    </b>

{% endif %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# User's Profile Picture #}

    {% if image %}

        <img class="rounded-2xl" src="data:image/png;base64,{{image}}" alt="image">

    {% endif %}

    {# TODO: Indicate which user's reviews we're looking at #}

    <h2 class="text-4xl font-bold opacity-50 my-4">{{ user.username }}'s Reviews</h2>

</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# TODO: Show all reviews made by the user #}

    <h4 class="text-2xl text-neutral-500">Number of Reviews: <b class="text-white">{{ reviews|length }}</b></h4>

    <table class="min-w-full divide-y divide-gray-200 mt-4">

        <thead class="bg-gray-50">

            <tr>

                <th style="border: 1px solid #fff4">Date</th>

                <th style="border: 1px solid #fff4">Album</th>

                <th style="border: 1px solid #fff4">Content</th>

            </tr>

        </thead>

        <tbody class="bg-white divide-y divide-gray-200">

            {% for review in reviews %}

            <tr>

                <td style="border: 1px solid #fff4">{{ review.date }}</td>

                <td style="border: 1px solid #fff4">{{ review.movie_title }}</td>

                <td style="border: 1px solid #fff4">{{ review.content }}</td>

            </tr>

            {% endfor %}

        </tbody>

    </table>

</div>

{% endblock %}